# fly.toml app configuration file generated for shop-ai on 2025-04-19T11:30:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shop-ai'
primary_region = 'ord'

[build]

[env]
  PORT = '3000'
  SCOPES = 'write_products'
  SHOPIFY_APP_URL = 'https://shop-ai.fly.dev'

[processes]
  app = "npm run docker-start"

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
