# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2a2ba6e7ada972054aa4e30f4d530a0d"
name = "ShopAI"
handle = "shopai-25"
application_url = "https://grows-stanley-taken-split.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://grows-stanley-taken-split.trycloudflare.com/auth/callback",
  "https://grows-stanley-taken-split.trycloudflare.com/auth/shopify/callback",
  "https://grows-stanley-taken-split.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://grows-stanley-taken-split.trycloudflare.com:3000"
subpath = "proxy"
prefix = "apps"
