# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "YOUR_NEW_API_KEY_HERE"
name = "ShopAI"
handle = "shopai-25"
application_url = "https://shop-ai.fly.dev"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shop-ai.fly.dev/auth",
  "https://shop-ai.fly.dev/auth/callback",
  "https://shop-ai.fly.dev/install"
]

[pos]
embedded = false

[app_proxy]
url = "https://shop-ai.fly.dev"
subpath = "proxy"
prefix = "apps"

# Theme App Extension Configuration
[extensions.theme]
type = "theme"
name = "ShopAI Theme Extension"
handle = "shopai-theme-extension"
path = "extensions/shop-ai"
