name = "ShopAI"
uid = "e9f0d1ea-e095-ef2c-a073-61b13018c6749423a030"
type = "theme"

# Specifies where this extension can be used in the theme editor
# Update: Let's allow blocks to be added directly to sections or as top-level sections
# extension_points = [
#   "section"
# ]

# --- Added capabilities ---
[capabilities]
network_access = true

# --- Added block definitions ---
blocks = [
  { name = "ask-me-anything", type = "@block" },
  { name = "review-summarizer", type = "@block" }
]

